---
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Coverage
          command: npm run coverage
      - run:
          name: Build
          command: npm run build
      - run:
          name: Semantic release
          command: npm run semantic-release
workflows:
    build:
      jobs:
        - build:
            context: semantic-release-npm
